### ISSUE TITLE
Disable GitHub Copilot  when using WordPress Hooks IntelliSense.

### ISSUE THREAD

**Issue by soderlind** [wp-hooks/vscode-wordpress-hooks#34]
I use Copilot (love it), but when I use your extension, Copilot creates unwanted noise (suggestions). I am uncertain if it works, but it would be nice if Copilot was disabled while using WordPress Hooks IntelliSense.

Maybe you can use `github.copilot.toggleCopilot` (toggle on / off)?

**Comment by johnbillion** [comment]
It seems that Copilot's mechanism for showing suggestions is a lot better than it was a couple of years ago, and doesn't step over this extension like it used to. Closing this off. Cheers!
