### ISSUE TITLE
Go to filter/action reference when click on hook name

### ISSUE THREAD

**Issue by parsakafi** [wp-hooks/vscode-wordpress-hooks#36]
Hello
This feature is very useful

<img width="683" alt="image" src="https://user-images.githubusercontent.com/7957513/180617635-65fb9aa4-dd82-4a6f-a48a-3b437dfba998.png">

**Comment by johnbillion** [comment]
Thanks for the suggestion @parsakafi but I'm happy with the current behaviour. Cheers!
